### ISSUE TITLE
ValueError during training

### ISSUE THREAD

**Issue by HanyuLi98** [aminabyaneh/stable-imitation-policy#1]
Hi Amin Abyaneh, 
![Snipaste_2024-07-10_02-58-55](https://github.com/aminabyaneh/stable-imitation-policy/assets/75526946/f8180cf7-b517-4d26-8dfc-8508b38f627e)

thanks for your great job! I have installed your package and wanted to test SNDS with my pc. However, I cannot run it because of "ValueError: arange: cannot compute length" (you can see in the following screenshot), could you please tell me how to fix it? 

By the way, conda env create -f environment.yml this command missed a "a" for yaml ：D.

Thanks a lot!

**Comment by aminabyaneh** [comment]
Hi Hanyu Li!

Thanks for reaching out with this issue. At the first glance, I see that there is an issue with plotting the Lyapunov candidate. You can comment the line which calls the "plot_contours" function and it should work.

I can look into it in more details next week, and will upload a patch to fix it asap!

Let me know if I can help further.
